language: php
sudo: false
dist: trusty
php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - travis_retry composer install -o --prefer-dist --no-interaction --no-progress --no-scripts --no-suggest

script:
  - composer lint
  - composer test
